sudo: required
services:
  - docker

before_install:
  - docker build -t conorburke/magnetar-test -f ./api/Dockerfile.dev ./api

script:
  - docker run conorburke/magnetar-test npm test -- --coverage

after_success:
  - docker build -t conorburke/magnetar-nginx ./nginx
  - docker build -t conorburke/magnetar-api ./api
  - docker build -t conorburke/magnetar-frontend ./frontend
  - docker build -t conorburke/magnetar-postgres ./db
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push conorburke/magnetar-nginx
  - docker push conorburke/magnetar-api
  - docker push conorburke/magnetar-frontend
  - docker push conorburke/magnetar-postgres

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: magnetar
  env: Magnetar-env
  bucket_name: elasticbeanstalk-us-east-2-234521127503
  bucket_path: upload-magnetar
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY